@url = "http://localhost:3000"


###register
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username":"pomaa",
    "password":"pomaa"
}


###login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username":"pomaa",
    "password":"pomaa"
}


####all books
GET http://localhost:3000/allbooks HTTP/1.1


###search books
GET http://localhost:3000/search?keyword=Faceless HTTP/1.1



###adding to cart
PUT http://localhost:3000/addToCart HTTP/1.1
Content-Type: application/json

{
    "user":"646c9c51afd887e6097823d2",
    "books":"646d0ee37fda1c7b8dce14b5",
    "quantity":"2"
}


###viewing cart
GET http://localhost:3000/viewcart/646c9c51afd887e6097823d2 HTTP/1.1


###clearing cart
DELETE http://localhost:3000/clearcart/646c9c51afd887e6097823d2 HTTP/1.1


###placing order
POST http://localhost:3000/order/646c9c51afd887e6097823d2 HTTP/1.1
Content-Type: application/json

{
    "address":"Tafo"
}


###make payments
POST http://localhost:3000/payment/646c9c51afd887e6097823d2 HTTP/1.1
Content-Type: application/json

{
    "payment":"55"
}


###viewing all purchased books
GET http://localhost:3000/purchased/646c9c51afd887e6097823d2 HTTP/1.1